package edu.exception;

public class ExceptionTest {
	public static void main(String[] args) throws Exception{
		Add add = new Add();
			add.addition(2, 2);
	}
}
